name: Build ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vanilla-os/pico:main
      volumes:
        - /proc:/proc
        - /:/run/host
      options: --privileged -it

    steps:
    - uses: actions/checkout@v4

    - name: Install needed packages
      run: apt update && apt install debootstrap -y

    - name: Build ISO
      run: ./build.sh etc/terraform.conf

    - name: Get current date
      run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> "$GITHUB_ENV"

    - uses: actions/upload-artifact@v4
      with:
        name: VanillaOS 2 Orchid ${{ env.CURRENT_DATE }}
        path: builds/
